FROM node:13.13.0

WORKDIR /app

COPY . .

RUN npm install -timeout=9999999

RUN apt-get update && apt-get -y upgrade

RUN wget -qO - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 

RUN apt-get install -y apt-transport-https

RUN echo "deb https://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list.d/google.list

CMD ["npm", "run", "start-all"]
